# Default values for Jackett.

image:
  repository: deepquestai/deepstack
  pullPolicy: IfNotPresent
  tag: cpu-2021.02.1

strategy:
  type: Recreate

services:
  main:
    enabled: true
    port:
      port: 5000

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

envTpl:
# Permissions Settings
  USER_ID: "{{ .Values.PUID }}"
  GROUP_ID: "{{ .Values.PGID }}"

env:
  # TZ: UTC
  VISION-FACE: True
  VISION-DETECTION: True
  VISION-SCENE: True
  MODELSTORE-DETECTION: "/modelstore/detection"    # Path to custom models (needs to be on documentation)
  MODE: High        # High|Medium|Low
  # ADMIN-KEY: "" # Deprecated since it got OpenSource? or optional?
  # API-KEY: "" # Deprecated since it got OpenSource? or optional?podSecurityContext:

persistence:
  config:
    enabled: true
    mountPath: "/datastore"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

## TrueCharts Values

ingress:
  main:
    enabled: false
